// Userspace side of the CPU profiler. Responsible for:
//   1. Loading the BPF program into the kernel
//   2. Opening perf events on every CPU and attaching the BPF program to them
//   3. Reading sample events from the kernel via a perf ring buffer
//   4. Printing sample data to stdout

#include <iostream>
#include <signal.h>
#include <unistd.h>
#include <bpf/libbpf.h>           // libbpf API: loading BPF programs, managing maps
#include <bpf/bpf.h>              // lower-level BPF syscall wrappers
#include <linux/perf_event.h>     // perf_event_attr and related constants
#include <sys/syscall.h>          // SYS_perf_event_open (no glibc wrapper exists)
#include "profiler.h"             // shared stack_event struct
#include "profiler.skel.h"        // auto-generated by bpftool from profiler.bpf.o

// Signals the main loop to exit cleanly on Ctrl+C.
// volatile tells the compiler not to cache this in a register —
// it can be changed asynchronously by the signal handler.
static volatile bool running = true;

static void handle_signal(int) {
    running = false;
}

// Called by the perf buffer library each time a new sample arrives from the kernel.
// data points to a stack_event struct written by the BPF program.
static void handle_event(void *ctx, int cpu, void *data, __u32 size) {
    struct stack_event *e = (struct stack_event *)data;
    printf("[cpu=%d] pid=%-6u comm=%-16s ts=%llu\n",
        cpu, e->pid, e->comm, e->timestamp_ns);
}

int main() {
    // Open, verify, and load the BPF program and maps into the kernel in one call.
    // profiler_bpf is a typed struct generated by bpftool — it has fields for each
    // map and program defined in profiler.bpf.c.
    struct profiler_bpf *skel = profiler_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "Failed to open and load BPF skeleton\n");
        return 1;
    }

    // Configure the perf event: sample based on CPU clock at 99hz.
    // 99 instead of 100 avoids lockstep sampling with other 100hz kernel timers.
    struct perf_event_attr attr = {};
    attr.type = PERF_TYPE_SOFTWARE;
    attr.config = PERF_COUNT_SW_CPU_CLOCK;
    attr.freq = 1;           // interpret sample_freq as hz, not a raw count
    attr.sample_freq = 99;

    // Open one perf event per CPU and attach the BPF program to each.
    // This ensures we sample every core, not just the one running this process.
    int num_cpus = libbpf_num_possible_cpus();
    int *perf_fds = new int[num_cpus];

    for (int i = 0; i < num_cpus; i++) {
        // perf_event_open has no glibc wrapper, so we call it directly via syscall.
        // -1 for pid means "any process", i is the CPU index, -1 for group_fd means no group.
        perf_fds[i] = syscall(SYS_perf_event_open, &attr, -1, i, -1, 0);
        struct bpf_link *link = bpf_program__attach_perf_event(
            skel->progs.profile_cpu, perf_fds[i]);
        (void)link;  // link intentionally not stored — program stays attached until fd is closed
    }

    // Set up the perf ring buffer reader. 8 is the number of memory pages per CPU
    // used for the buffer. handle_event is called for each sample that arrives.
    struct perf_buffer_opts pb_opts = {};
    pb_opts.sample_cb = handle_event;
    struct perf_buffer *pb = perf_buffer__new(bpf_map__fd(skel->maps.events), 8, &pb_opts);

    signal(SIGINT, handle_signal);
    printf("Profiling... Ctrl+C to stop.\n");

    // Poll for new events every 100ms until Ctrl+C.
    while (running) {
        perf_buffer__poll(pb, 100);
    }

    // Clean up in reverse order of creation.
    perf_buffer__free(pb);
    for (int i = 0; i < num_cpus; i++) close(perf_fds[i]);
    delete[] perf_fds;
    profiler_bpf__destroy(skel);
    return 0;
}
