#include "collector.h"

#include <bpf/bpf.h>
#include <bpf/libbpf.h>
#include <cstdio>
#include <linux/perf_event.h>
#include <sys/syscall.h>
#include <unistd.h>

// Auto-generated by bpftool from bpf/profiler.bpf.c — provides the typed
// profiler_bpf struct and open/load/destroy functions.
#include "profiler.skel.h"

// Thin wrapper passed as context to the perf buffer callback so it can
// reach the Collector instance without a global variable.
struct CallbackContext {
  EventCallback cb;
};

// Called by the perf buffer library for each sample arriving from the kernel.
static void on_sample(void *ctx, int cpu, void *data, __u32 size) {
  auto *c = static_cast<CallbackContext *>(ctx);
  c->cb(*static_cast<stack_event *>(data));
}

Collector::Collector(int sample_freq, EventCallback cb)
    : sample_freq_(sample_freq), cb_(std::move(cb)) {}

Collector::~Collector() {}

bool Collector::start() {
  // Load the BPF program and maps into the kernel.
  struct profiler_bpf *skel = profiler_bpf__open_and_load();
  if (!skel) {
    fprintf(stderr, "Failed to open and load BPF skeleton\n");
    return false;
  }
  stack_traces_fd_ = bpf_map__fd(skel->maps.stack_traces);

  // Configure a software perf event that fires at sample_freq_ hz.
  struct perf_event_attr attr = {};
  attr.type = PERF_TYPE_SOFTWARE;
  attr.config = PERF_COUNT_SW_CPU_CLOCK;
  attr.freq = 1;
  attr.sample_freq = sample_freq_;

  // Open one perf event per CPU and attach the BPF program to each.
  int num_cpus = libbpf_num_possible_cpus();
  int *perf_fds = new int[num_cpus];
  for (int i = 0; i < num_cpus; i++) {
    perf_fds[i] = syscall(SYS_perf_event_open, &attr, -1, i, -1, 0);
    bpf_program__attach_perf_event(skel->progs.profile_cpu, perf_fds[i]);
  }

  // Set up the perf ring buffer with our sample callback.
  CallbackContext ctx{cb_};
  struct perf_buffer_opts pb_opts = {};
  pb_opts.sample_cb = on_sample;
  pb_opts.ctx = &ctx;
  struct perf_buffer *pb =
      perf_buffer__new(bpf_map__fd(skel->maps.events), 8, &pb_opts);

  running_ = true;
  while (running_) {
    perf_buffer__poll(pb, 100);
  }

  // Clean up in reverse order of creation.
  perf_buffer__free(pb);
  for (int i = 0; i < num_cpus; i++)
    close(perf_fds[i]);
  delete[] perf_fds;
  profiler_bpf__destroy(skel);
  return true;
}

void Collector::stop() { running_ = false; }

int Collector::stack_traces_fd() const { return stack_traces_fd_; }
